---
title: "LME (interaction) (ET5)"
format:
  html:
    toc: true
---

Extended Data Table 5 is the output of linear mixed-effects models run on all complete cases, with an interaction term for visitId and compliance in the [helper-lme](helper-lmm.qmd) script using the model `(value ~ age at consent + smoking pack years + visitId*compliance + (1|subjectId)`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, eval = T)
```

```{r libraries}
library(dplyr)
library(here)
here::i_am('et5.qmd')
```


```{r}
load(here("out/out_lmm_factor.Rdata"))
source(here("src/renameVarsLME.R"))
out_lmm<- renameVarsLME(out_lmm)
```

```{r}
DT::datatable(out_lmm[["Interaction model with packyears"]] |> 
                dplyr::filter(!is.na(`p.value_visitIdM6:compliancehigher compliance`)) |> 
                dplyr::arrange(`p.value_visitIdM6:compliancehigher compliance`) |> 
                dplyr::select(assay, variable, `estimate_visitIdM4:compliancehigher compliance`,
                              `estimate_visitIdM4:compliancehigher compliance`,
                              `estimate_visitIdM6:compliancehigher compliance`,
                              `p.value_visitIdM2:compliancehigher compliance`,
                              `p.value_visitIdM4:compliancehigher compliance`,
                              `p.value_visitIdM6:compliancehigher compliance`))
```