---
title: "TG repository: smoking cessation"
---

Code repository for TG figures and exploratory analysis code (smoking cessation).

## Helper functions and prep

These pages describe big scripts run over all variables and save the outputs. This means models are standardised and outputs can be pulled from the saved scripts.

Examples include:

* [correlation of variables with age at baseline](helper-corr-age-at-baseline.qmd)
* [correlation of variables with smoking pack years (spy) at baseline][helper-corr-spy.qmd]
* [correlation of variables with daily cigarettes at baseline][helper-corr-cig-at-baseline.qmd]
* [Wilcoxon tests over all variables](helper-wilcoxon-tests.qmd)
* [linear mixed models over all variables](helper-lmm.qmd)
* [sensitivity analyse][helper-sensitivity.qmd]
* [repeated measures correlation](helper-rmcorr.qmd)

## Figure and Table scripts

These pages provide the code for the final figures.

* [Figure 1: Overview](fig1-overview.qmd)
  + [Supplementary Figure 1](fig1-overview.qmd)
* [Figure 2: Clinical and immune](fig2-clin-imm.qmd)
  + [Supplementary Figure 2](fig2-clin-imm.qmd)
  + [Supplementary Figure 3](fig2-clin-imm.qmd)
* [Figure 3: Epigenetics](fig3-epi.qmd)
  + [Supplementary Figure 4](fig3-epi.qmd)
* [Figure 4: Metabolome](fig4-metab.qmd)
  + [Supplementary Figure 5](fig4-metab.qmd)
* [Figure 5: Microbiome](fig5-microb-revised.qmd)
  + [Supplementary Figure 6](fig5-microb-revised.qmd)
  + [Supplementary Figure 7](fig5-microb-revised.qmd)
* [Figure 6: Integration](fig6-integration.qmd)
  + [Supplementary Figure 8](fig6-integration.qmd)
  + [Supplementary Figure 9](fig6-integration.qmd)
  
(Supplementary) Tables are located in the tables/ subdirectory.